apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fooapp
  name: fooapp
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: fooapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fooapp
    spec:
      serviceAccountName: test
      containers:
      - image: gcr.io/root-cortex-387409/python-backend-boilerplate@sha256:b6473a2afa881989519246e8e42186632474f442a67e9cb7e0d5d196f5118843
        imagePullPolicy: IfNotPresent
        name: python-backend-boilerplate
        env:
          - name: GCS_PROJECT
            value: "root-cortex-387409"
        resources:
          limits:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 1Gi
          requests:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 1Gi
